### ISSUE TITLE
Support for `mtl` 2.2.2

### ISSUE THREAD

**Issue by srid** [lucasvreis/ondim#16]
Could `mtl` 2.2.2 be supported? Currently the library requires the latest:

https://github.com/lucasvreis/ondim/blob/f2d3bf663640d79dd4fc1320ba45249820b675a0/ondim.cabal#L71

Without this, I'm unable to use ondim on a Nix project.

**Comment by srid** [comment]
Or is GHC 9.4 not supported?

**Comment by lucasvreis** [comment]
GHC 9.4 is supported, but I was using the new `Writer.CPS` module (see that #17 failed). Perhaps I'll use `State` instead and also hide the constructor of `ExpansionMap`.

**Comment by lucasvreis** [comment]
@srid a note: the module structure and the names of many things are being considerably improved in #18
